project:
  type: website

website:
  title: "Diabetes"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: models.qmd
        text: Models
      - href: graphs.qmd
        text: Graphs
      - href: sources.qmd
        text: Sources
      - about.qmd
      - icon: github
        href: https://github.com/vibhadara/Diabetes
        aria-label: GitHub
      
      
format:
  html:
    theme: cosmo
    fontsize: 1.14em
    linestretch: 1.8
    css: styles.css
    toc: true



